### ISSUE TITLE
Visualize Tab: Limit View Not Implemented As Intended

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/internal-data-portal#70]
Relates to:
- https://github.com/icefoganalytics/internal-data-portal/blob/main/_Design/WireFrames%2C%20Internal%20Data%20Portal%2C%202024-01-08.pdf
- https://github.com/icefoganalytics/internal-data-portal/blob/main/_Design/User%20Stories%2C%20Internal%20Data%20Portal%2C%202024-01-08.docx
- [0004, Dataset Preview, 2024-05-21](https://docs.google.com/document/d/1wsgiX_fG8QIC07nbS4qjcuHb3IWri7xX7viqMP23xRE)

# Context

**Is your feature request related to a problem? Please describe.**
The limit data view is not meant to limit the search function rather it is to limit what a normal system user can seen in the visualization field.
![image](https://github.com/icefoganalytics/internal-data-portal/assets/89539008/d9bc21f8-4b99-4496-9960-75fb56fcb67e)

The first question is do you want to limit what data the normal user sees on the visualization tab. (I think the term “on data search” was misleading).
So if the answer is yes…they can derive what fields they want to exclude/not show in the visualization tab and how many rows it will show.

If the user has approved access these limitations are removed.

Would likely make sense to include a show no visualization as well, so that the data owner can choose to show no demo data.
I think for all the above cases this search function should be removed.

**Describe the solution you'd like**

1. Re-imagine `VisualizationControl` fields as exclusion from view, rather than exclusion from search.
    - `isDownloadableAsCsv` - stays the same
    - `hasSearchCustomizations` -> `hasPreviewCustomizations`
    - `hasFieldsExcludedFromSearch` -> `hasFieldsExcludedFromPreview` - on by default, but is a quick way to disable all field exclusions - when toggled this should probably update the DatasetField show/hide flag?
    - `hasSearchRowLimits` -> `hasPreviewRowLimit` - do we still need this?
    - `searchRowLimitMaximum` -> `previewRowLimit` - do we still need this?
    - `importSizeLimit` -> changes import size limit, though is separate from export size limit of full dataset.
`DatasetField` - `isExcludedFromSearch` -> `isExcludeFromPreview` and should be on by default for all fields when imported.
2. Add DatasetEntryPreview model to serve dataset preview that is separate from:
    1. dataset export
    2. dataset visualization after access is granted
    Preview table is populated from DatasetEntry + DatasetField exclusions + VisualizationControl settings.

## Questions

1. Should preview table should be hidden when preview customization is turned off? Or should a default preview be provided instead? If so I should probably update the flag name to "show dataset preview" instead of "enable preview customization".

**Additional context**
![image](https://github.com/icefoganalytics/internal-data-portal/assets/23045206/7aa9d51b-5c8c-4cbf-8152-f76264ec3b49)

**Comment by klondikemarlen** [comment]
@dpdavids Ah too bad. I was a 50/50 on meaning, but leaned towards search.
On the plus side, it's relatively easy to switch the meaning from the code side.

In regards to the row limit, I'm not sure that still has meaning, given that I'm paginating the data.
What effect did you imagine that the row limiter would create?
Was it optimization? Or something else?
If the results _are_ to be limited, there needs to be an ordering applied, or the limit will just silently and inexplicably drop data.

**Comment by klondikemarlen** [comment]
@dpdavids Based on the update project scope/direction described in [0003, IDP and Storing Data, 2024-03-27](https://docs.google.com/document/d/1S6BPUqVuYNLXMOXME36os2i0LnrpRyCmWE5ihXqGix0/edit) we could re-purpose the row limit as the size of the import?

e.g. set the default to 100 as per discussion, and provide the ability to increase/decrease as needed?

**Comment by dpdavids** [comment]
that sounds good @klondikemarlen

**Comment by klondikemarlen** [comment]
@dpdavids Reading this again, is the visualization tab supposed to provide users access to the dataset _before_ they are granted "true" access?

**Comment by dpdavids** [comment]
@klondikemarlen yes this was originally meant as a view **before** access.  The data owner/system admin or ba can decide to limit any of these.  your example makes sense.

**Comment by klondikemarlen** [comment]
Hmmm, that's very different from my current implementation of the system. I'll reflect on the full implications and update this ticket to reflect the work required.

**Comment by klondikemarlen** [comment]
# Dataset Entry Policy Scoping

If preview customization and result limiting is on, then
I need to limit the results, and set the offset to 0 always?

Should I just build a custom table for dataset entry preview?

1. limited size
2. limited fields (from previewable dataset fields)

```sql
CREATE VIEW dataset_entry_previews AS
WITH limited_entries AS (
    SELECT
        dataset_entries.id AS dataset_entry_id,
        dataset_entries.dataset_id,
        dataset_entries.json_data,
        ROW_NUMBER() OVER (PARTITION BY dataset_entries.dataset_id ORDER BY dataset_entries.id) AS row_num
    FROM
        dataset_entries
    WHERE
        dataset_entries.deleted_at IS NULL
),
json_data_parsed AS (
    SELECT
        limited_entries.dataset_entry_id,
        limited_entries.dataset_id,
        dataset_fields.name AS field_name,
        JSON_VALUE(limited_entries.json_data, CONCAT('$.', dataset_fields.name)) AS field_value
    FROM
        limited_entries
    INNER JOIN
        dataset_fields ON dataset_fields.dataset_id = limited_entries.dataset_id
    WHERE
        dataset_fields.is_excluded_from_preview = 0
),
filtered_json AS (
    SELECT
        dataset_entry_id,
        dataset_id,
        STRING_AGG(CONCAT('"', field_name, '":', ISNULL(QUOTENAME(field_value, '"'), 'null')), ',') WITHIN GROUP (ORDER BY field_name) AS filtered_json_data
    FROM
        json_data_parsed
    GROUP BY
        dataset_entry_id,
        dataset_id
)
SELECT
    limited_entries.dataset_entry_id,
    limited_entries.dataset_id,
    CONCAT('{', filtered_json.filtered_json_data, '}') AS json_data
FROM
    limited_entries
INNER JOIN
    filtered_json ON filtered_json.dataset_entry_id = limited_entries.dataset_entry_id
INNER JOIN
    visualization_controls ON visualization_controls.dataset_id = limited_entries.dataset_id
WHERE
    limited_entries.row_num <= visualization_controls.preview_row_limit
    AND visualization_controls.deleted_at IS NULL;
```

But since this is pretty hard to read, I'm going to build a regular database table and update it as needed.
