### ISSUE TITLE
Position information populate from directory but need to be overwritten

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/internal-data-portal#73]
For both owner and support positions need to populate from the selected user in the directory api.  They need the ability to overwrite this position in the case the directory api is incorrect.

**Comment by klondikemarlen** [comment]
This is a bit of a complicated one from a data integrity vs. usability standpoint.

The current feature is possible with the current interface via:
As a System Admin:
1. importing a user
2. updating the user's information
3. creating the dataset with the updated user.

From an usability perspective, I could:
1. make it possible to imported user in real time from the datasets creation form 
2. have edits to the various dataset owner fields update the user on dataset creation, or in real time.

From a security perspective though, this breaks security around user management, effectively giving "dataset owner" the ability to create/update arbitrary users.

We could limit the exposer, by giving them the ability to:
1. only create users as part of dataset creation, but not edit them after the fact.
2. only create users for emails that don't already exist.

@dpdavids Thoughts?

**Comment by dpdavids** [comment]
Hi @klondikemarlen I think if you can include a hyperlink to update their own user information that is sufficient.  But as an FYI an data owner and data support users do not need to be system users.  The example would be when a business analyst enters the information on behalf of the unit, particularly when it is open or subscribe, where no approval is required.  If they are a system user and their name is in either of these fields they have the ability to manage the record.

**Comment by dpdavids** [comment]
These would just be potential users.  Everyone within YG can be a user.  There may be cases where a business analyst will enter the dataset.  The dataset does not belong to them rather someone else would be the expert.  The owner of the dataset or the support user may or may not be IDP users.  But they are the people that understand the dataset the most.  ideally they would both be users but it is not manditory.

**Comment by klondikemarlen** [comment]
[0005, Setting User Metadata, 2024-06-06](https://docs.google.com/document/d/1sKpJ20D6X5LgEywI5Gmbex5NOkZEyoe5OeScoQaZJIw/edit?pli=1#heading=h.vexcbj3n6fn0)

**Comment by klondikemarlen** [comment]
Closing in favour of multiple linked tickets.
