### ISSUE TITLE
BUG: Department drop down showing # not name

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/internal-data-portal#74]
# Context

Once a dataset is saved the Department field is converted to a number.
![image](https://github.com/icefoganalytics/internal-data-portal/assets/89539008/090a4e7b-c8d7-4359-8163-b40ec06d1bd7)

EDIT 1: On the https://internal-data-portal.ynet.gov.yk.ca/datasets/yg-buildings/description/manage page, on navigation from create form, the Department field doesn't load and only displays the department ID instead of the department name. This might be due to the number of entries returned from the back-end.

EDIT 2: this bug is cause by the ID of the user group being outside of the 10 element paginated lookup response. This effectively prevents the end user from picking any department not in the first 10 in the database. Also effects division/branch/unit, though for these the limit is the first 10 for with a given parent.

**Comment by klondikemarlen** [comment]
Would you mind providing the URL of the page this occurred on?

**Comment by dpdavids** [comment]
https://internal-data-portal.ynet.gov.yk.ca/datasets/yg-buildings/description/manage

**Comment by klondikemarlen** [comment]
Thank you!
