### ISSUE TITLE
Live Data conditional date selector

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/internal-data-portal#76]
If the data is Live = yes than no published date is required if live = no then the published date must be populated.

**Comment by klondikemarlen** [comment]
@dpdavids Could you please provide some more context for this bug? Please see the bug template at https://github.com/icefoganalytics/internal-data-portal/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by dpdavids** [comment]
**Describe the bug**
The expected interaction is when the "live data?" is select the published date selector and fields should not appear (or be greyed out).  If the "live data?" is not selected the published date should appear and be a mandatory field.

**To Reproduce**
Steps to reproduce the behavior:
1. Edit a dataset
2. Click on 'live date?'

**Expected behavior**
See above.

**Screenshots**
![image](https://github.com/icefoganalytics/internal-data-portal/assets/89539008/0300f2c0-7d05-49ef-9d52-ad7f0fc04e3f)

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by klondikemarlen** [comment]
Thank you!
