### ISSUE TITLE
UX: Owner region has save others have check

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/internal-data-portal#78]
I noticed that the owner region on the description page has a save button and the other regions dont have saves (well they have the circle icon on the top).  From a user perspective I might think that the owner save button will save everything on the page.  I am not sure if it requires a different interaction or something.  But it would be nice if it could be consistent with the rest of the page.

**Comment by klondikemarlen** [comment]
Yeah, I created the auto-save feature after building that section, and haven't made it back there to normalize it.
Thanks for adding this so I can keep track of it!

As a future note, I think it would be a good idea to specify auto-save as a requirement, or to include save buttons in the wireframes. Save buttons are usually safer from an accessibility standpoint, but it was easier for me to set up auto-save than to figure out where to put save buttons in the UI; so now we have auto-save.
