### ISSUE TITLE
Search box populate with dashboard keyword

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/internal-data-portal#85]
Relates to:
Search

# Context

**Is your feature request related to a problem? Please describe.**
When a user does a keyword search on the main dashboard it takes them to the data page with the data limited to the search.  In the search field it says click to clear or remove query. 
![image](https://github.com/icefoganalytics/internal-data-portal/assets/89539008/9c7ec962-e5e1-4a93-8f84-19f67943cdfb)

**Describe the solution you'd like**
I think it would be more user friendly to include the search in this field.  In the picture above it should show "buildings"

**Comment by klondikemarlen** [comment]
Relates to https://github.com/icefoganalytics/internal-data-portal/issues/42. 

@dpdavids The dataset search field hasn't been implemented yet, and from the wireframe, I wasn't clear on what the implementation was supposed to look like.

Would you like me to replicate the search features from the dashboard? Or add additional fields?

See the old Proof app as an example of what search can look like:
Filters open
![image](https://github.com/icefoganalytics/internal-data-portal/assets/23045206/5a6d2e82-acf1-4bb3-b61c-97d1b06952fd)

Filters closed
![image](https://github.com/icefoganalytics/internal-data-portal/assets/23045206/99575ff6-6a8b-4755-b95f-a08529c5dd61)
