### ISSUE TITLE
Download CSV name dataset name

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/internal-data-portal#86]
Relates to:
CSV Download

# Context

**Is your feature request related to a problem? Please describe.**
When a user downloads a csv from the application the export is named something like "Export, Dataset Entries, 2024-03-29".  If the user downloaded a different dataset it would have a similiar name.  Potentially be confusing when they download a lot and go to use it.

**Describe the solution you'd like**
Can the download be renamed Dataset name - date or something more descriptive  eg. Buildings-2024-03-29.

**Comment by klondikemarlen** [comment]
I went with the format
`{data type}, {dataset name}, {ISO short date}`
e.g.
- `Export, Employee Directory, 2024-04-02.csv`
